---
name: Deploy-Dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'  # All markdown files in the repository

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: npm clean-install
      - run: npm run build --if-present

      - name: Install CloudFoundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx --directory=/usr/local/bin
          cf --version

      - name: Setup CF CLI
        run: |
          cf api https://api.fr.cloud.gov
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s give-dev

      - run: cf push --vars-file vars.yaml
